"""Edited_table_Fff

Revision ID: 1d4b835f48f2
Revises: 97ec402ef81c
Create Date: 2024-06-25 15:27:59.667736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4b835f48f2'
down_revision: Union[str, None] = '97ec402ef81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fff', 'fffs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fff', sa.Column('fffs', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
