"""Deleted_table_Fff

Revision ID: 33c8e27f6f7d
Revises: 3b937294d244
Create Date: 2024-06-25 15:27:12.624074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c8e27f6f7d'
down_revision: Union[str, None] = '3b937294d244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fff')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fff',
    sa.Column('ddd', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('ddd', name='fff_pkey')
    )
    # ### end Alembic commands ###
