"""Edited_table_Fff

Revision ID: 97ec402ef81c
Revises: be50d9cdc99f
Create Date: 2024-06-25 15:27:50.645789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ec402ef81c'
down_revision: Union[str, None] = 'be50d9cdc99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fff', 'dsfds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fff', sa.Column('dsfds', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
