"""Add_table_Fff

Revision ID: be50d9cdc99f
Revises: 33c8e27f6f7d
Create Date: 2024-06-25 15:27:39.479782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be50d9cdc99f'
down_revision: Union[str, None] = '33c8e27f6f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fff',
    sa.Column('dddd', sa.Integer(), nullable=False),
    sa.Column('fffs', sa.Integer(), nullable=True),
    sa.Column('dsfds', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('dddd')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fff')
    # ### end Alembic commands ###
