"""Add_table_Xs

Revision ID: ed09fc88935e
Revises: 
Create Date: 2024-06-25 15:27:04.687871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed09fc88935e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xs',
    sa.Column('dcdc', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('dcdc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xs')
    # ### end Alembic commands ###
